#!/usr/bin/env bash
# Rust formatting gate.
#
# Checks each tracked Rust file individually instead of running `cargo fmt --check`, for
# two reasons:
#
#   1. `src-tauri/libs/**` is vendored and must not be formatted (GOLDEN-RULES R7).
#   2. `src/schema.rs` is generated by `diesel print-schema` with 4-space indentation,
#      which conflicts with the repository's `tab_spaces = 2`. rustfmt has no stable way
#      to exclude a single path: `ignore` in rustfmt.toml requires nightly,
#      `#![rustfmt::skip]` is an unstable custom inner attribute, and rustfmt follows
#      `mod schema;` from main.rs into the file regardless of the argument list.
#
# Excluding the file from the *output* after checking each file individually is the only
# approach that works on stable rustfmt, and it means regenerating schema.rs produces no
# spurious diff.
#
# Usage: bash scripts/harness/check-rustfmt.sh
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT/src-tauri" || exit 1

if ! command -v rustfmt >/dev/null 2>&1; then
  echo "rustfmt not installed; run: rustup component add rustfmt" >&2
  exit 1
fi

fail=0
for f in $(git ls-files '*.rs' | grep -vE '^libs/'); do
  out=$(rustfmt --check --edition 2021 "$f" 2>&1 | grep '^Diff in' | grep -v 'src/schema\.rs')
  if [ -n "$out" ]; then
    printf '%s\n' "$out"
    fail=1
  fi
done

if [ "$fail" -eq 0 ]; then
  echo "rustfmt: OK"
fi
exit $fail
