#!/usr/bin/env node
/**
 * ESLint ratchet gate.
 *
 * Runs ESLint and compares the per-file error counts against the baseline recorded in
 * `docs/harness/eslint-baseline.json`. The gate fails when:
 *   - any file exceeds its baselined error count (a regression), or
 *   - a file has errors but is not in the baseline at all (new offender), or
 *   - the total exceeds the baselined total.
 *
 * It deliberately does NOT fail on baselined errors, so the gate can be enforced today
 * against a codebase with pre-existing debt, while still blocking any new debt. Baselines
 * may shrink, never grow (docs/harness/GOLDEN-RULES.md R9).
 *
 * Warnings are reported but never fail the build: `no-explicit-any` is a W6 ratchet target.
 *
 * Usage:
 *   node scripts/harness/lint-ratchet.mjs            # enforce against the baseline
 *   node scripts/harness/lint-ratchet.mjs --report   # print the current distribution
 *   node scripts/harness/lint-ratchet.mjs --update    # rewrite the baseline (requires intent)
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const BASELINE = path.join(ROOT, 'docs/harness/eslint-baseline.json')
const ARGS = new Set(process.argv.slice(2))

function runEslint() {
  const out = path.join(ROOT, 'node_modules/.cache/eslint-report.json')
  try {
    // --format json with -o avoids interleaving npm's stderr warnings into stdout.
    execFileSync(
      'npx',
      ['--no-install', 'eslint', '.', '--ext', '.ts,.tsx', '--format', 'json', '-o', out],
      { cwd: ROOT, stdio: ['ignore', 'ignore', 'ignore'] }
    )
  } catch (e) {
    // ESLint exits non-zero when it finds problems; the report is still written.
    if (!existsSync(out)) throw e
  }
  return JSON.parse(readFileSync(out, 'utf8'))
}

const report = runEslint()

/** file -> { errors, warnings, byRule } */
const current = {}
let totalErrors = 0
let totalWarnings = 0
const ruleTotals = {}

for (const entry of report) {
  const rel = path.relative(ROOT, entry.filePath)
  if (entry.errorCount === 0 && entry.warningCount === 0) continue
  const byRule = {}
  for (const m of entry.messages) {
    const sev = m.severity === 2 ? 'errors' : 'warnings'
    byRule[m.ruleId] = byRule[m.ruleId] || { errors: 0, warnings: 0 }
    byRule[m.ruleId][sev]++
    const key = (m.severity === 2 ? 'E:' : 'W:') + (m.ruleId ?? 'parse')
    ruleTotals[key] = (ruleTotals[key] || 0) + 1
  }
  current[rel] = { errors: entry.errorCount, warnings: entry.warningCount, byRule }
  totalErrors += entry.errorCount
  totalWarnings += entry.warningCount
}

if (ARGS.has('--report') || ARGS.has('--update')) {
  console.log(
    `errors ${totalErrors} · warnings ${totalWarnings} · files ${
      Object.keys(current).length
    }`
  )
  console.log('')
  console.log('by rule:')
  for (const [k, v] of Object.entries(ruleTotals).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${String(v).padStart(4)}  ${k}`)
  }
}

if (ARGS.has('--update')) {
  const payload = {
    $comment:
      'ESLint ratchet baseline. Generated by scripts/harness/lint-ratchet.mjs --update. ' +
      'Counts may only go DOWN (docs/harness/GOLDEN-RULES.md R9). See docs/harness/DEBT-BASELINE.md.',
    generatedFor: 'eslint 8 (eslintrc format)',
    totalErrors,
    totalWarnings,
    byRule: Object.fromEntries(Object.entries(ruleTotals).sort((a, b) => b[1] - a[1])),
    files: Object.fromEntries(
      Object.entries(current).sort((a, b) => b[1].errors - a[1].errors)
    ),
  }
  writeFileSync(BASELINE, JSON.stringify(payload, null, 2) + '\n')
  console.log(`\nwrote ${path.relative(ROOT, BASELINE)}`)
  process.exit(0)
}

if (!existsSync(BASELINE)) {
  console.error(
    `lint-ratchet: no baseline at ${path.relative(ROOT, BASELINE)}.\n` +
      `  Generate the initial one with: node scripts/harness/lint-ratchet.mjs --update`
  )
  process.exit(1)
}

const baseline = JSON.parse(readFileSync(BASELINE, 'utf8'))
const regressions = []
const newOffenders = []

for (const [file, info] of Object.entries(current)) {
  const allowed = baseline.files[file]
  if (!allowed) {
    newOffenders.push(`${file} (${info.errors} errors, not in baseline)`)
  } else if (info.errors > allowed.errors) {
    regressions.push(`${file}: ${info.errors} errors, baseline allows ${allowed.errors}`)
  }
}

const failures = []
if (regressions.length) {
  failures.push(
    'Error count increased above the baseline (fix the errors, or make the case in DEBT-BASELINE.md):'
  )
  failures.push(...regressions.map(r => `  ${r}`))
}
if (newOffenders.length) {
  failures.push('New files with lint errors (not baselined):')
  failures.push(...newOffenders.map(r => `  ${r}`))
}
if (totalErrors > baseline.totalErrors) {
  failures.push(`Total errors ${totalErrors} exceeds baseline ${baseline.totalErrors}`)
}

if (failures.length) {
  console.error('LINT RATCHET FAILED\n')
  console.error(failures.join('\n'))
  console.error(
    `\nRun \`npm run lint:fix\` for the auto-fixable subset, or inspect with:\n` +
      `  node scripts/harness/lint-ratchet.mjs --report`
  )
  process.exit(1)
}

const improved = baseline.totalErrors - totalErrors
console.log(
  `lint-ratchet: OK — ${totalErrors} errors (baseline ${baseline.totalErrors}` +
    `${improved > 0 ? `, improved by ${improved}` : ''}), ${totalWarnings} warnings, ` +
    `${Object.keys(current).length} files`
)
if (improved > 0) {
  console.log(`  Tighten the ratchet: node scripts/harness/lint-ratchet.mjs --update`)
}
